# Generated by Django 3.1 on 2020-09-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('userType', models.CharField(max_length=100)),
                ('organizationName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'logintable',
            },
        ),
    ]
